CREATE TABLE ETL_WATERMARK (
    TARGET_NAME       VARCHAR2(128)  PRIMARY KEY,
    WM_COLUMN         VARCHAR2(128)  NOT NULL,
    LAST_WM           VARCHAR2(64),
    LAST_RUN_STARTED  TIMESTAMP,
    LAST_RUN_FINISHED TIMESTAMP,
    LAST_STATUS       VARCHAR2(16),
    ROWS_LOADED       NUMBER DEFAULT 0,
    ERROR_MESSAGE     VARCHAR2(4000)
);
