CREATE TABLE STG_GL_CODE_COMBINATIONS (
    CODE_COMBINATION_ID          NUMBER,
    LAST_UPDATE_DATE             TIMESTAMP,
    CHART_OF_ACCOUNTS_ID         NUMBER,
    ACCOUNT_TYPE                 VARCHAR2(1),
    ENABLED_FLAG                 VARCHAR2(1),
    SUMMARY_FLAG                 VARCHAR2(1),
    SEGMENT1                     VARCHAR2(25),
    SEGMENT2                     VARCHAR2(25),
    SEGMENT3                     VARCHAR2(25),
    SEGMENT4                     VARCHAR2(25),
    SEGMENT5                     VARCHAR2(25),
    SEGMENT6                     VARCHAR2(25),
    SEGMENT7                     VARCHAR2(25),
    SEGMENT8                     VARCHAR2(25),
    SEGMENT9                     VARCHAR2(25),
    SEGMENT10                    VARCHAR2(25),
    DESCRIPTION                  VARCHAR2(240),
    START_DATE_ACTIVE            DATE,
    END_DATE_ACTIVE              DATE,
    DETAIL_POSTING_ALLOWED_FLAG  VARCHAR2(1),
    DETAIL_BUDGETING_ALLOWED_FLAG VARCHAR2(1),
    CONCATENATED_SEGMENTS        VARCHAR2(4000),
    FINANCIAL_CATEGORY           VARCHAR2(30),
    CREATION_DATE                TIMESTAMP,
    CREATED_BY                   VARCHAR2(64)
);
