CREATE TABLE T_PO_HEADERS (
    PO_HEADER_ID               NUMBER(18,0)   PRIMARY KEY,
    LAST_UPDATE_DATE           TIMESTAMP(6)   NOT NULL,
    LAST_UPDATED_BY            VARCHAR2(256)  NOT NULL,
    CREATION_DATE              TIMESTAMP(6)   NOT NULL,
    CREATED_BY                 VARCHAR2(256)  NOT NULL,
    SEGMENT1                   VARCHAR2(120)  NOT NULL,
    PRC_BU_ID                  NUMBER(18,0)   NOT NULL,
    REQ_BU_ID                  NUMBER(18,0),
    TYPE_LOOKUP_CODE           VARCHAR2(100)  NOT NULL,
    DOCUMENT_STATUS            VARCHAR2(100)  NOT NULL,
    AGENT_ID                   NUMBER(18,0)   NOT NULL,
    VENDOR_ID                  NUMBER(18,0),
    VENDOR_SITE_ID             NUMBER(18,0),
    VENDOR_CONTACT_ID          NUMBER(18,0),
    SHIP_TO_LOCATION_ID        NUMBER(18,0),
    BILL_TO_LOCATION_ID        NUMBER(18,0),
    BILLTO_BU_ID               NUMBER(18,0),
    SOLDTO_LE_ID               NUMBER(18,0),
    TERMS_ID                   NUMBER(18,0),
    CURRENCY_CODE              VARCHAR2(60),
    RATE_TYPE                  VARCHAR2(120),
    RATE_DATE                  DATE,
    RATE                       NUMBER,
    FOB_LOOKUP_CODE            VARCHAR2(120),
    FREIGHT_TERMS_LOOKUP_CODE  VARCHAR2(120),
    START_DATE                 DATE,
    END_DATE                   DATE,
    BLANKET_TOTAL_AMOUNT       NUMBER,
    AMOUNT_LIMIT               NUMBER,
    AMOUNT_RELEASED            NUMBER,
    MIN_RELEASE_AMOUNT         NUMBER,
    REVISION_NUM               NUMBER,
    REVISED_DATE               DATE,
    APPROVED_FLAG              VARCHAR2(4),
    APPROVED_DATE              DATE,
    CANCEL_FLAG                VARCHAR2(4),
    CLOSED_DATE                DATE,
    FROZEN_FLAG                VARCHAR2(4),
    CONFIRMING_ORDER_FLAG      VARCHAR2(4),
    ACCEPTANCE_REQUIRED_FLAG   VARCHAR2(4),
    ACCEPTANCE_DUE_DATE        DATE,
    NOTE_TO_VENDOR             VARCHAR2(4000),
    NOTE_TO_RECEIVER           VARCHAR2(4000),
    VENDOR_ORDER_NUM           VARCHAR2(100),
    COMMENTS                   VARCHAR2(960),
    SUBMIT_DATE                DATE,
    CHANGE_SUMMARY             VARCHAR2(4000),
    FUNDS_STATUS               VARCHAR2(100)
);
